//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AtlasW2SEntities : DbContext
    {
        public AtlasW2SEntities()
            : base("name=AtlasW2SEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<USERDETAIL> USERDETAILs { get; set; }
        public virtual DbSet<USERTYPE> USERTYPEs { get; set; }
        public virtual DbSet<W2S__Master_Enquiry> W2S__Master_Enquiry { get; set; }
        public virtual DbSet<W2S__Master_Enquiry_History> W2S__Master_Enquiry_History { get; set; }
        public virtual DbSet<W2S__Master_Enquiry_Range_Mapping> W2S__Master_Enquiry_Range_Mapping { get; set; }
        public virtual DbSet<W2S__Master_Enquiry_Visit_> W2S__Master_Enquiry_Visit_ { get; set; }
        public virtual DbSet<W2S__Master_Navigation> W2S__Master_Navigation { get; set; }
        public virtual DbSet<W2S__Master_Navigation_Role_Mapping> W2S__Master_Navigation_Role_Mapping { get; set; }
        public virtual DbSet<W2S_Customer_CompressorRoom_Mapping> W2S_Customer_CompressorRoom_Mapping { get; set; }
        public virtual DbSet<W2S_Customer_Contct_Person_Mapping> W2S_Customer_Contct_Person_Mapping { get; set; }
        public virtual DbSet<W2S_Customer_Industry_Mapping> W2S_Customer_Industry_Mapping { get; set; }
        public virtual DbSet<W2S_Customer_Master> W2S_Customer_Master { get; set; }
        public virtual DbSet<W2S_List> W2S_List { get; set; }
        public virtual DbSet<W2S_Master_Absent> W2S_Master_Absent { get; set; }
        public virtual DbSet<W2S_Master_City> W2S_Master_City { get; set; }
        public virtual DbSet<W2S_Master_Competitor> W2S_Master_Competitor { get; set; }
        public virtual DbSet<W2S_Master_EnquirySource> W2S_Master_EnquirySource { get; set; }
        public virtual DbSet<W2S_Master_EnquiryType> W2S_Master_EnquiryType { get; set; }
        public virtual DbSet<W2S_Master_Holiday> W2S_Master_Holiday { get; set; }
        public virtual DbSet<W2S_Master_Industry> W2S_Master_Industry { get; set; }
        public virtual DbSet<W2S_Master_Nav_Role_Map> W2S_Master_Nav_Role_Map { get; set; }
        public virtual DbSet<W2S_Master_Navigation> W2S_Master_Navigation { get; set; }
        public virtual DbSet<W2S_Master_Product> W2S_Master_Product { get; set; }
        public virtual DbSet<W2S_Master_RangeMapping> W2S_Master_RangeMapping { get; set; }
        public virtual DbSet<W2S_Master_Resource> W2S_Master_Resource { get; set; }
        public virtual DbSet<W2S_Master_Resource_Map> W2S_Master_Resource_Map { get; set; }
        public virtual DbSet<W2S_Master_Segment> W2S_Master_Segment { get; set; }
        public virtual DbSet<W2S_Master_SubRange> W2S_Master_SubRange { get; set; }
        public virtual DbSet<W2S_Opportunity> W2S_Opportunity { get; set; }
        public virtual DbSet<W2S_Opportunity_Competitor> W2S_Opportunity_Competitor { get; set; }
        public virtual DbSet<W2S_Opportunity_Document> W2S_Opportunity_Document { get; set; }
        public virtual DbSet<W2S_Opportunity_Product> W2S_Opportunity_Product { get; set; }
        public virtual DbSet<W2S_Opportunity_Quotation> W2S_Opportunity_Quotation { get; set; }
        public virtual DbSet<W2S_Opportunity_Visits> W2S_Opportunity_Visits { get; set; }
        public virtual DbSet<W2S_Master_Designation> W2S_Master_Designation { get; set; }
        public virtual DbSet<W2S_Master_State> W2S_Master_State { get; set; }
        public virtual DbSet<W2S_Master_Zone> W2S_Master_Zone { get; set; }
    
        [DbFunction("AtlasW2SEntities", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string input, string character)
        {
            var inputParameter = input != null ?
                new ObjectParameter("Input", input) :
                new ObjectParameter("Input", typeof(string));
    
            var characterParameter = character != null ?
                new ObjectParameter("Character", character) :
                new ObjectParameter("Character", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[AtlasW2SEntities].[SplitString](@Input, @Character)", inputParameter, characterParameter);
        }
    
        public virtual ObjectResult<SP_Change_Password_Result> SP_Change_Password(string password, string nEWPassword, Nullable<int> user_ID, string aCTION)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nEWPasswordParameter = nEWPassword != null ?
                new ObjectParameter("NEWPassword", nEWPassword) :
                new ObjectParameter("NEWPassword", typeof(string));
    
            var user_IDParameter = user_ID.HasValue ?
                new ObjectParameter("User_ID", user_ID) :
                new ObjectParameter("User_ID", typeof(int));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Change_Password_Result>("SP_Change_Password", passwordParameter, nEWPasswordParameter, user_IDParameter, aCTIONParameter);
        }
    
        public virtual ObjectResult<SP_ChangePassword_Result> SP_ChangePassword(string password, string confirmPassword)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var confirmPasswordParameter = confirmPassword != null ?
                new ObjectParameter("ConfirmPassword", confirmPassword) :
                new ObjectParameter("ConfirmPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ChangePassword_Result>("SP_ChangePassword", passwordParameter, confirmPasswordParameter);
        }
    
        public virtual int SP_Customer_Master(string custName, string custAddress, string custPinCode, string custLongitude, string custLatitude, string custGSTNNo, string custCmprsdAirApp, string typeOfIndustry, string endProduct, string compRoomDetails, string city, string state, string type, Nullable<int> custId, ObjectParameter result)
        {
            var custNameParameter = custName != null ?
                new ObjectParameter("CustName", custName) :
                new ObjectParameter("CustName", typeof(string));
    
            var custAddressParameter = custAddress != null ?
                new ObjectParameter("CustAddress", custAddress) :
                new ObjectParameter("CustAddress", typeof(string));
    
            var custPinCodeParameter = custPinCode != null ?
                new ObjectParameter("CustPinCode", custPinCode) :
                new ObjectParameter("CustPinCode", typeof(string));
    
            var custLongitudeParameter = custLongitude != null ?
                new ObjectParameter("CustLongitude", custLongitude) :
                new ObjectParameter("CustLongitude", typeof(string));
    
            var custLatitudeParameter = custLatitude != null ?
                new ObjectParameter("CustLatitude", custLatitude) :
                new ObjectParameter("CustLatitude", typeof(string));
    
            var custGSTNNoParameter = custGSTNNo != null ?
                new ObjectParameter("CustGSTNNo", custGSTNNo) :
                new ObjectParameter("CustGSTNNo", typeof(string));
    
            var custCmprsdAirAppParameter = custCmprsdAirApp != null ?
                new ObjectParameter("CustCmprsdAirApp", custCmprsdAirApp) :
                new ObjectParameter("CustCmprsdAirApp", typeof(string));
    
            var typeOfIndustryParameter = typeOfIndustry != null ?
                new ObjectParameter("TypeOfIndustry", typeOfIndustry) :
                new ObjectParameter("TypeOfIndustry", typeof(string));
    
            var endProductParameter = endProduct != null ?
                new ObjectParameter("EndProduct", endProduct) :
                new ObjectParameter("EndProduct", typeof(string));
    
            var compRoomDetailsParameter = compRoomDetails != null ?
                new ObjectParameter("CompRoomDetails", compRoomDetails) :
                new ObjectParameter("CompRoomDetails", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var custIdParameter = custId.HasValue ?
                new ObjectParameter("CustId", custId) :
                new ObjectParameter("CustId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Customer_Master", custNameParameter, custAddressParameter, custPinCodeParameter, custLongitudeParameter, custLatitudeParameter, custGSTNNoParameter, custCmprsdAirAppParameter, typeOfIndustryParameter, endProductParameter, compRoomDetailsParameter, cityParameter, stateParameter, typeParameter, custIdParameter, result);
        }
    
        public virtual int SP_Enquiry_Source(Nullable<int> enquirysource_id, string enquirysource_name, string enquirysource_desc, string type, ObjectParameter result)
        {
            var enquirysource_idParameter = enquirysource_id.HasValue ?
                new ObjectParameter("enquirysource_id", enquirysource_id) :
                new ObjectParameter("enquirysource_id", typeof(int));
    
            var enquirysource_nameParameter = enquirysource_name != null ?
                new ObjectParameter("enquirysource_name", enquirysource_name) :
                new ObjectParameter("enquirysource_name", typeof(string));
    
            var enquirysource_descParameter = enquirysource_desc != null ?
                new ObjectParameter("enquirysource_desc", enquirysource_desc) :
                new ObjectParameter("enquirysource_desc", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Enquiry_Source", enquirysource_idParameter, enquirysource_nameParameter, enquirysource_descParameter, typeParameter, result);
        }
    
        public virtual ObjectResult<SP_GetAllUser_Result> SP_GetAllUser(string emailID, string aCTION)
        {
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAllUser_Result>("SP_GetAllUser", emailIDParameter, aCTIONParameter);
        }
    
        public virtual ObjectResult<SP_GetAllUser2_Result> SP_GetAllUser2(Nullable<int> oTP, string aCTION)
        {
            var oTPParameter = oTP.HasValue ?
                new ObjectParameter("OTP", oTP) :
                new ObjectParameter("OTP", typeof(int));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAllUser2_Result>("SP_GetAllUser2", oTPParameter, aCTIONParameter);
        }
    
        public virtual int SP_Industry_Master(Nullable<int> industrysource_id, string industrysource_name, string industrysource_desc, string type, ObjectParameter result)
        {
            var industrysource_idParameter = industrysource_id.HasValue ?
                new ObjectParameter("Industrysource_id", industrysource_id) :
                new ObjectParameter("Industrysource_id", typeof(int));
    
            var industrysource_nameParameter = industrysource_name != null ?
                new ObjectParameter("Industrysource_name", industrysource_name) :
                new ObjectParameter("Industrysource_name", typeof(string));
    
            var industrysource_descParameter = industrysource_desc != null ?
                new ObjectParameter("Industrysource_desc", industrysource_desc) :
                new ObjectParameter("Industrysource_desc", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Industry_Master", industrysource_idParameter, industrysource_nameParameter, industrysource_descParameter, typeParameter, result);
        }
    
        public virtual int SP_InsUpdDelCustomer(string prodname, string proddesc, string type, Nullable<int> prodid, ObjectParameter result)
        {
            var prodnameParameter = prodname != null ?
                new ObjectParameter("prodname", prodname) :
                new ObjectParameter("prodname", typeof(string));
    
            var proddescParameter = proddesc != null ?
                new ObjectParameter("proddesc", proddesc) :
                new ObjectParameter("proddesc", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var prodidParameter = prodid.HasValue ?
                new ObjectParameter("prodid", prodid) :
                new ObjectParameter("prodid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsUpdDelCustomer", prodnameParameter, proddescParameter, typeParameter, prodidParameter, result);
        }
    
        public virtual int SP_InsUpdDelIndustry_Master(Nullable<int> industrysource_id, string industrysource_name, string industrysource_desc, string type, ObjectParameter result)
        {
            var industrysource_idParameter = industrysource_id.HasValue ?
                new ObjectParameter("Industrysource_id", industrysource_id) :
                new ObjectParameter("Industrysource_id", typeof(int));
    
            var industrysource_nameParameter = industrysource_name != null ?
                new ObjectParameter("Industrysource_name", industrysource_name) :
                new ObjectParameter("Industrysource_name", typeof(string));
    
            var industrysource_descParameter = industrysource_desc != null ?
                new ObjectParameter("Industrysource_desc", industrysource_desc) :
                new ObjectParameter("Industrysource_desc", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsUpdDelIndustry_Master", industrysource_idParameter, industrysource_nameParameter, industrysource_descParameter, typeParameter, result);
        }
    
        public virtual int SP_Product_Master(string prodname, string proddesc, string type, Nullable<int> prodid, ObjectParameter result)
        {
            var prodnameParameter = prodname != null ?
                new ObjectParameter("prodname", prodname) :
                new ObjectParameter("prodname", typeof(string));
    
            var proddescParameter = proddesc != null ?
                new ObjectParameter("proddesc", proddesc) :
                new ObjectParameter("proddesc", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var prodidParameter = prodid.HasValue ?
                new ObjectParameter("prodid", prodid) :
                new ObjectParameter("prodid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Product_Master", prodnameParameter, proddescParameter, typeParameter, prodidParameter, result);
        }
    
        public virtual ObjectResult<SP_USERAUTHFOR_AtlasSales_Result> SP_USERAUTHFOR_AtlasSales(Nullable<int> user_ID, string password, string nEWPassword, string aCTION)
        {
            var user_IDParameter = user_ID.HasValue ?
                new ObjectParameter("User_ID", user_ID) :
                new ObjectParameter("User_ID", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nEWPasswordParameter = nEWPassword != null ?
                new ObjectParameter("NEWPassword", nEWPassword) :
                new ObjectParameter("NEWPassword", typeof(string));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_USERAUTHFOR_AtlasSales_Result>("SP_USERAUTHFOR_AtlasSales", user_IDParameter, passwordParameter, nEWPasswordParameter, aCTIONParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Calender_Result> W2S_SP_Calender(string action, Nullable<int> pK_Navigaion_Id, string navigation_Menu_Name, string navigation_Description, string navigation_URL, Nullable<int> navigation_Parent_Id, Nullable<int> fK_Designation_Id, Nullable<int> isActive, Nullable<int> created_By, Nullable<System.DateTime> created_Date, Nullable<int> modified_By, Nullable<System.DateTime> modified_Date, Nullable<int> rOLE_ID, Nullable<int> uSERID)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var pK_Navigaion_IdParameter = pK_Navigaion_Id.HasValue ?
                new ObjectParameter("PK_Navigaion_Id", pK_Navigaion_Id) :
                new ObjectParameter("PK_Navigaion_Id", typeof(int));
    
            var navigation_Menu_NameParameter = navigation_Menu_Name != null ?
                new ObjectParameter("Navigation_Menu_Name", navigation_Menu_Name) :
                new ObjectParameter("Navigation_Menu_Name", typeof(string));
    
            var navigation_DescriptionParameter = navigation_Description != null ?
                new ObjectParameter("Navigation_Description", navigation_Description) :
                new ObjectParameter("Navigation_Description", typeof(string));
    
            var navigation_URLParameter = navigation_URL != null ?
                new ObjectParameter("Navigation_URL", navigation_URL) :
                new ObjectParameter("Navigation_URL", typeof(string));
    
            var navigation_Parent_IdParameter = navigation_Parent_Id.HasValue ?
                new ObjectParameter("Navigation_Parent_Id", navigation_Parent_Id) :
                new ObjectParameter("Navigation_Parent_Id", typeof(int));
    
            var fK_Designation_IdParameter = fK_Designation_Id.HasValue ?
                new ObjectParameter("FK_Designation_Id", fK_Designation_Id) :
                new ObjectParameter("FK_Designation_Id", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(int));
    
            var created_DateParameter = created_Date.HasValue ?
                new ObjectParameter("Created_Date", created_Date) :
                new ObjectParameter("Created_Date", typeof(System.DateTime));
    
            var modified_ByParameter = modified_By.HasValue ?
                new ObjectParameter("Modified_By", modified_By) :
                new ObjectParameter("Modified_By", typeof(int));
    
            var modified_DateParameter = modified_Date.HasValue ?
                new ObjectParameter("Modified_Date", modified_Date) :
                new ObjectParameter("Modified_Date", typeof(System.DateTime));
    
            var rOLE_IDParameter = rOLE_ID.HasValue ?
                new ObjectParameter("ROLE_ID", rOLE_ID) :
                new ObjectParameter("ROLE_ID", typeof(int));
    
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Calender_Result>("W2S_SP_Calender", actionParameter, pK_Navigaion_IdParameter, navigation_Menu_NameParameter, navigation_DescriptionParameter, navigation_URLParameter, navigation_Parent_IdParameter, fK_Designation_IdParameter, isActiveParameter, created_ByParameter, created_DateParameter, modified_ByParameter, modified_DateParameter, rOLE_IDParameter, uSERIDParameter);
        }
    
        public virtual int W2S_SP_Enquiry_Master(string enqryNo, Nullable<int> enqryType, string source, string productOffered, string range, string visitType, string nextVisitDate, string nextVisitTime, string recordNotes, Nullable<int> enqryId, string type, ObjectParameter result)
        {
            var enqryNoParameter = enqryNo != null ?
                new ObjectParameter("EnqryNo", enqryNo) :
                new ObjectParameter("EnqryNo", typeof(string));
    
            var enqryTypeParameter = enqryType.HasValue ?
                new ObjectParameter("EnqryType", enqryType) :
                new ObjectParameter("EnqryType", typeof(int));
    
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            var productOfferedParameter = productOffered != null ?
                new ObjectParameter("ProductOffered", productOffered) :
                new ObjectParameter("ProductOffered", typeof(string));
    
            var rangeParameter = range != null ?
                new ObjectParameter("Range", range) :
                new ObjectParameter("Range", typeof(string));
    
            var visitTypeParameter = visitType != null ?
                new ObjectParameter("VisitType", visitType) :
                new ObjectParameter("VisitType", typeof(string));
    
            var nextVisitDateParameter = nextVisitDate != null ?
                new ObjectParameter("NextVisitDate", nextVisitDate) :
                new ObjectParameter("NextVisitDate", typeof(string));
    
            var nextVisitTimeParameter = nextVisitTime != null ?
                new ObjectParameter("NextVisitTime", nextVisitTime) :
                new ObjectParameter("NextVisitTime", typeof(string));
    
            var recordNotesParameter = recordNotes != null ?
                new ObjectParameter("RecordNotes", recordNotes) :
                new ObjectParameter("RecordNotes", typeof(string));
    
            var enqryIdParameter = enqryId.HasValue ?
                new ObjectParameter("EnqryId", enqryId) :
                new ObjectParameter("EnqryId", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("W2S_SP_Enquiry_Master", enqryNoParameter, enqryTypeParameter, sourceParameter, productOfferedParameter, rangeParameter, visitTypeParameter, nextVisitDateParameter, nextVisitTimeParameter, recordNotesParameter, enqryIdParameter, typeParameter, result);
        }
    
        public virtual ObjectResult<W2S_SP_Insert_OTP_Result> W2S_SP_Insert_OTP(Nullable<int> oTP, string aCTION)
        {
            var oTPParameter = oTP.HasValue ?
                new ObjectParameter("OTP", oTP) :
                new ObjectParameter("OTP", typeof(int));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Insert_OTP_Result>("W2S_SP_Insert_OTP", oTPParameter, aCTIONParameter);
        }
    
        public virtual ObjectResult<W2S_SP_LeaveType_Result> W2S_SP_LeaveType(string aCTION)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_LeaveType_Result>("W2S_SP_LeaveType", aCTIONParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_Competitor_Result> W2S_SP_Master_Competitor(string fK_Competitor_Type_Id, string competitor_Name, string competitor_Desc, Nullable<int> isActive, string aCTION, Nullable<int> pK_Competitor_Id, Nullable<int> created_By, Nullable<System.DateTime> created_Date, Nullable<int> modified_By, Nullable<System.DateTime> modified_Date)
        {
            var fK_Competitor_Type_IdParameter = fK_Competitor_Type_Id != null ?
                new ObjectParameter("FK_Competitor_Type_Id", fK_Competitor_Type_Id) :
                new ObjectParameter("FK_Competitor_Type_Id", typeof(string));
    
            var competitor_NameParameter = competitor_Name != null ?
                new ObjectParameter("Competitor_Name", competitor_Name) :
                new ObjectParameter("Competitor_Name", typeof(string));
    
            var competitor_DescParameter = competitor_Desc != null ?
                new ObjectParameter("Competitor_Desc", competitor_Desc) :
                new ObjectParameter("Competitor_Desc", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(int));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var pK_Competitor_IdParameter = pK_Competitor_Id.HasValue ?
                new ObjectParameter("PK_Competitor_Id", pK_Competitor_Id) :
                new ObjectParameter("PK_Competitor_Id", typeof(int));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(int));
    
            var created_DateParameter = created_Date.HasValue ?
                new ObjectParameter("Created_Date", created_Date) :
                new ObjectParameter("Created_Date", typeof(System.DateTime));
    
            var modified_ByParameter = modified_By.HasValue ?
                new ObjectParameter("Modified_By", modified_By) :
                new ObjectParameter("Modified_By", typeof(int));
    
            var modified_DateParameter = modified_Date.HasValue ?
                new ObjectParameter("Modified_Date", modified_Date) :
                new ObjectParameter("Modified_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_Competitor_Result>("W2S_SP_Master_Competitor", fK_Competitor_Type_IdParameter, competitor_NameParameter, competitor_DescParameter, isActiveParameter, aCTIONParameter, pK_Competitor_IdParameter, created_ByParameter, created_DateParameter, modified_ByParameter, modified_DateParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> W2S_SP_Master_Customer(Nullable<int> pK_Cust_Id, string cust_Name, string cust_Address_Line1, string cust_Address_Line2, Nullable<int> fK_Zone_Id, Nullable<int> fK_State_Id, Nullable<int> fK_City_Id, string cust_GSTN_No, string cust_Cmprsd_Air_App, string cust_End_Product, Nullable<int> fK_Cust_Id, Nullable<int> fK_Cust_CntctPrson_Dsgntn_Id, string cust_CntctPrson_Name, string cust_CntctPrson_Contact_No, string cust_CntctPrson_Email_Id, Nullable<int> cust_Cmprsor_RoomDetails, string cust_Cmprsor_Model, string cust_Cmprsor_Mfg_Year, string cust_Cmprsor_Commissioning_Year, Nullable<int> cust_Cmprsor_Status, Nullable<int> created_By, Nullable<int> fK_Industry_Type_Id, Nullable<int> pK_Cust_CntctPrson_Mapng_Id, Nullable<int> pK_Cust_Cmprsor_Mapng_Id, string visitingCardPath, string action)
        {
            var pK_Cust_IdParameter = pK_Cust_Id.HasValue ?
                new ObjectParameter("PK_Cust_Id", pK_Cust_Id) :
                new ObjectParameter("PK_Cust_Id", typeof(int));
    
            var cust_NameParameter = cust_Name != null ?
                new ObjectParameter("Cust_Name", cust_Name) :
                new ObjectParameter("Cust_Name", typeof(string));
    
            var cust_Address_Line1Parameter = cust_Address_Line1 != null ?
                new ObjectParameter("Cust_Address_Line1", cust_Address_Line1) :
                new ObjectParameter("Cust_Address_Line1", typeof(string));
    
            var cust_Address_Line2Parameter = cust_Address_Line2 != null ?
                new ObjectParameter("Cust_Address_Line2", cust_Address_Line2) :
                new ObjectParameter("Cust_Address_Line2", typeof(string));
    
            var fK_Zone_IdParameter = fK_Zone_Id.HasValue ?
                new ObjectParameter("FK_Zone_Id", fK_Zone_Id) :
                new ObjectParameter("FK_Zone_Id", typeof(int));
    
            var fK_State_IdParameter = fK_State_Id.HasValue ?
                new ObjectParameter("FK_State_Id", fK_State_Id) :
                new ObjectParameter("FK_State_Id", typeof(int));
    
            var fK_City_IdParameter = fK_City_Id.HasValue ?
                new ObjectParameter("FK_City_Id", fK_City_Id) :
                new ObjectParameter("FK_City_Id", typeof(int));
    
            var cust_GSTN_NoParameter = cust_GSTN_No != null ?
                new ObjectParameter("Cust_GSTN_No", cust_GSTN_No) :
                new ObjectParameter("Cust_GSTN_No", typeof(string));
    
            var cust_Cmprsd_Air_AppParameter = cust_Cmprsd_Air_App != null ?
                new ObjectParameter("Cust_Cmprsd_Air_App", cust_Cmprsd_Air_App) :
                new ObjectParameter("Cust_Cmprsd_Air_App", typeof(string));
    
            var cust_End_ProductParameter = cust_End_Product != null ?
                new ObjectParameter("Cust_End_Product", cust_End_Product) :
                new ObjectParameter("Cust_End_Product", typeof(string));
    
            var fK_Cust_IdParameter = fK_Cust_Id.HasValue ?
                new ObjectParameter("FK_Cust_Id", fK_Cust_Id) :
                new ObjectParameter("FK_Cust_Id", typeof(int));
    
            var fK_Cust_CntctPrson_Dsgntn_IdParameter = fK_Cust_CntctPrson_Dsgntn_Id.HasValue ?
                new ObjectParameter("FK_Cust_CntctPrson_Dsgntn_Id", fK_Cust_CntctPrson_Dsgntn_Id) :
                new ObjectParameter("FK_Cust_CntctPrson_Dsgntn_Id", typeof(int));
    
            var cust_CntctPrson_NameParameter = cust_CntctPrson_Name != null ?
                new ObjectParameter("Cust_CntctPrson_Name", cust_CntctPrson_Name) :
                new ObjectParameter("Cust_CntctPrson_Name", typeof(string));
    
            var cust_CntctPrson_Contact_NoParameter = cust_CntctPrson_Contact_No != null ?
                new ObjectParameter("Cust_CntctPrson_Contact_No", cust_CntctPrson_Contact_No) :
                new ObjectParameter("Cust_CntctPrson_Contact_No", typeof(string));
    
            var cust_CntctPrson_Email_IdParameter = cust_CntctPrson_Email_Id != null ?
                new ObjectParameter("Cust_CntctPrson_Email_Id", cust_CntctPrson_Email_Id) :
                new ObjectParameter("Cust_CntctPrson_Email_Id", typeof(string));
    
            var cust_Cmprsor_RoomDetailsParameter = cust_Cmprsor_RoomDetails.HasValue ?
                new ObjectParameter("Cust_Cmprsor_RoomDetails", cust_Cmprsor_RoomDetails) :
                new ObjectParameter("Cust_Cmprsor_RoomDetails", typeof(int));
    
            var cust_Cmprsor_ModelParameter = cust_Cmprsor_Model != null ?
                new ObjectParameter("Cust_Cmprsor_Model", cust_Cmprsor_Model) :
                new ObjectParameter("Cust_Cmprsor_Model", typeof(string));
    
            var cust_Cmprsor_Mfg_YearParameter = cust_Cmprsor_Mfg_Year != null ?
                new ObjectParameter("Cust_Cmprsor_Mfg_Year", cust_Cmprsor_Mfg_Year) :
                new ObjectParameter("Cust_Cmprsor_Mfg_Year", typeof(string));
    
            var cust_Cmprsor_Commissioning_YearParameter = cust_Cmprsor_Commissioning_Year != null ?
                new ObjectParameter("Cust_Cmprsor_Commissioning_Year", cust_Cmprsor_Commissioning_Year) :
                new ObjectParameter("Cust_Cmprsor_Commissioning_Year", typeof(string));
    
            var cust_Cmprsor_StatusParameter = cust_Cmprsor_Status.HasValue ?
                new ObjectParameter("Cust_Cmprsor_Status", cust_Cmprsor_Status) :
                new ObjectParameter("Cust_Cmprsor_Status", typeof(int));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(int));
    
            var fK_Industry_Type_IdParameter = fK_Industry_Type_Id.HasValue ?
                new ObjectParameter("FK_Industry_Type_Id", fK_Industry_Type_Id) :
                new ObjectParameter("FK_Industry_Type_Id", typeof(int));
    
            var pK_Cust_CntctPrson_Mapng_IdParameter = pK_Cust_CntctPrson_Mapng_Id.HasValue ?
                new ObjectParameter("PK_Cust_CntctPrson_Mapng_Id", pK_Cust_CntctPrson_Mapng_Id) :
                new ObjectParameter("PK_Cust_CntctPrson_Mapng_Id", typeof(int));
    
            var pK_Cust_Cmprsor_Mapng_IdParameter = pK_Cust_Cmprsor_Mapng_Id.HasValue ?
                new ObjectParameter("PK_Cust_Cmprsor_Mapng_Id", pK_Cust_Cmprsor_Mapng_Id) :
                new ObjectParameter("PK_Cust_Cmprsor_Mapng_Id", typeof(int));
    
            var visitingCardPathParameter = visitingCardPath != null ?
                new ObjectParameter("VisitingCardPath", visitingCardPath) :
                new ObjectParameter("VisitingCardPath", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("W2S_SP_Master_Customer", pK_Cust_IdParameter, cust_NameParameter, cust_Address_Line1Parameter, cust_Address_Line2Parameter, fK_Zone_IdParameter, fK_State_IdParameter, fK_City_IdParameter, cust_GSTN_NoParameter, cust_Cmprsd_Air_AppParameter, cust_End_ProductParameter, fK_Cust_IdParameter, fK_Cust_CntctPrson_Dsgntn_IdParameter, cust_CntctPrson_NameParameter, cust_CntctPrson_Contact_NoParameter, cust_CntctPrson_Email_IdParameter, cust_Cmprsor_RoomDetailsParameter, cust_Cmprsor_ModelParameter, cust_Cmprsor_Mfg_YearParameter, cust_Cmprsor_Commissioning_YearParameter, cust_Cmprsor_StatusParameter, created_ByParameter, fK_Industry_Type_IdParameter, pK_Cust_CntctPrson_Mapng_IdParameter, pK_Cust_Cmprsor_Mapng_IdParameter, visitingCardPathParameter, actionParameter);
        }
    
        public virtual int W2S_SP_Master_Enquiry(string enquirySource_Name, string enquirySource_Desc, string aCTION, Nullable<int> enquirySource_Id)
        {
            var enquirySource_NameParameter = enquirySource_Name != null ?
                new ObjectParameter("EnquirySource_Name", enquirySource_Name) :
                new ObjectParameter("EnquirySource_Name", typeof(string));
    
            var enquirySource_DescParameter = enquirySource_Desc != null ?
                new ObjectParameter("EnquirySource_Desc", enquirySource_Desc) :
                new ObjectParameter("EnquirySource_Desc", typeof(string));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var enquirySource_IdParameter = enquirySource_Id.HasValue ?
                new ObjectParameter("EnquirySource_Id", enquirySource_Id) :
                new ObjectParameter("EnquirySource_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("W2S_SP_Master_Enquiry", enquirySource_NameParameter, enquirySource_DescParameter, aCTIONParameter, enquirySource_IdParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_Enquiry_Source_Result> W2S_SP_Master_Enquiry_Source(string enquiry_Source_Name, string enquiry_Source_Desc, Nullable<int> isActive, string aCTION, Nullable<int> enquiry_Source_Id)
        {
            var enquiry_Source_NameParameter = enquiry_Source_Name != null ?
                new ObjectParameter("Enquiry_Source_Name", enquiry_Source_Name) :
                new ObjectParameter("Enquiry_Source_Name", typeof(string));
    
            var enquiry_Source_DescParameter = enquiry_Source_Desc != null ?
                new ObjectParameter("Enquiry_Source_Desc", enquiry_Source_Desc) :
                new ObjectParameter("Enquiry_Source_Desc", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(int));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var enquiry_Source_IdParameter = enquiry_Source_Id.HasValue ?
                new ObjectParameter("Enquiry_Source_Id", enquiry_Source_Id) :
                new ObjectParameter("Enquiry_Source_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_Enquiry_Source_Result>("W2S_SP_Master_Enquiry_Source", enquiry_Source_NameParameter, enquiry_Source_DescParameter, isActiveParameter, aCTIONParameter, enquiry_Source_IdParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_Enquiry_Type_Result> W2S_SP_Master_Enquiry_Type(string enquiry_Type_Name, string enquiry_Type_Description, Nullable<int> isActive, string aCTION, Nullable<int> enquiry_Type_Id)
        {
            var enquiry_Type_NameParameter = enquiry_Type_Name != null ?
                new ObjectParameter("Enquiry_Type_Name", enquiry_Type_Name) :
                new ObjectParameter("Enquiry_Type_Name", typeof(string));
    
            var enquiry_Type_DescriptionParameter = enquiry_Type_Description != null ?
                new ObjectParameter("Enquiry_Type_Description", enquiry_Type_Description) :
                new ObjectParameter("Enquiry_Type_Description", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(int));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var enquiry_Type_IdParameter = enquiry_Type_Id.HasValue ?
                new ObjectParameter("Enquiry_Type_Id", enquiry_Type_Id) :
                new ObjectParameter("Enquiry_Type_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_Enquiry_Type_Result>("W2S_SP_Master_Enquiry_Type", enquiry_Type_NameParameter, enquiry_Type_DescriptionParameter, isActiveParameter, aCTIONParameter, enquiry_Type_IdParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_GetAll_RangeType_Result> W2S_SP_Master_GetAll_RangeType(string aCTION)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_GetAll_RangeType_Result>("W2S_SP_Master_GetAll_RangeType", aCTIONParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_Holiday_Result> W2S_SP_Master_Holiday(string action, Nullable<int> pK_Holiday_Id, string holiday_Name, string holiday_Description, Nullable<System.DateTime> holiday_Date, Nullable<int> fK_Dealer_Id, string year, Nullable<int> isActive, Nullable<int> created_By, Nullable<System.DateTime> created_Date, Nullable<int> modified_By, Nullable<System.DateTime> modified_Date)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var pK_Holiday_IdParameter = pK_Holiday_Id.HasValue ?
                new ObjectParameter("PK_Holiday_Id", pK_Holiday_Id) :
                new ObjectParameter("PK_Holiday_Id", typeof(int));
    
            var holiday_NameParameter = holiday_Name != null ?
                new ObjectParameter("Holiday_Name", holiday_Name) :
                new ObjectParameter("Holiday_Name", typeof(string));
    
            var holiday_DescriptionParameter = holiday_Description != null ?
                new ObjectParameter("Holiday_Description", holiday_Description) :
                new ObjectParameter("Holiday_Description", typeof(string));
    
            var holiday_DateParameter = holiday_Date.HasValue ?
                new ObjectParameter("Holiday_Date", holiday_Date) :
                new ObjectParameter("Holiday_Date", typeof(System.DateTime));
    
            var fK_Dealer_IdParameter = fK_Dealer_Id.HasValue ?
                new ObjectParameter("FK_Dealer_Id", fK_Dealer_Id) :
                new ObjectParameter("FK_Dealer_Id", typeof(int));
    
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(int));
    
            var created_DateParameter = created_Date.HasValue ?
                new ObjectParameter("Created_Date", created_Date) :
                new ObjectParameter("Created_Date", typeof(System.DateTime));
    
            var modified_ByParameter = modified_By.HasValue ?
                new ObjectParameter("Modified_By", modified_By) :
                new ObjectParameter("Modified_By", typeof(int));
    
            var modified_DateParameter = modified_Date.HasValue ?
                new ObjectParameter("Modified_Date", modified_Date) :
                new ObjectParameter("Modified_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_Holiday_Result>("W2S_SP_Master_Holiday", actionParameter, pK_Holiday_IdParameter, holiday_NameParameter, holiday_DescriptionParameter, holiday_DateParameter, fK_Dealer_IdParameter, yearParameter, isActiveParameter, created_ByParameter, created_DateParameter, modified_ByParameter, modified_DateParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_Industry_Result> W2S_SP_Master_Industry(string industry_Name, string industry_Desc, Nullable<int> isActive, string aCTION, Nullable<int> industry_Id)
        {
            var industry_NameParameter = industry_Name != null ?
                new ObjectParameter("Industry_Name", industry_Name) :
                new ObjectParameter("Industry_Name", typeof(string));
    
            var industry_DescParameter = industry_Desc != null ?
                new ObjectParameter("Industry_Desc", industry_Desc) :
                new ObjectParameter("Industry_Desc", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(int));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var industry_IdParameter = industry_Id.HasValue ?
                new ObjectParameter("Industry_Id", industry_Id) :
                new ObjectParameter("Industry_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_Industry_Result>("W2S_SP_Master_Industry", industry_NameParameter, industry_DescParameter, isActiveParameter, aCTIONParameter, industry_IdParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_LIST_Result> W2S_SP_Master_LIST(string action, Nullable<int> fK_Zone_Id, Nullable<int> fK_State_Id)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var fK_Zone_IdParameter = fK_Zone_Id.HasValue ?
                new ObjectParameter("FK_Zone_Id", fK_Zone_Id) :
                new ObjectParameter("FK_Zone_Id", typeof(int));
    
            var fK_State_IdParameter = fK_State_Id.HasValue ?
                new ObjectParameter("FK_State_Id", fK_State_Id) :
                new ObjectParameter("FK_State_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_LIST_Result>("W2S_SP_Master_LIST", actionParameter, fK_Zone_IdParameter, fK_State_IdParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_Navigation_Result> W2S_SP_Master_Navigation(string action, Nullable<int> pK_Navigaion_Id, string navigation_Menu_Name, string navigation_Description, string navigation_URL, Nullable<int> navigation_Parent_Id, Nullable<int> fK_Designation_Id, Nullable<int> isActive, Nullable<int> created_By, Nullable<System.DateTime> created_Date, Nullable<int> modified_By, Nullable<System.DateTime> modified_Date)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var pK_Navigaion_IdParameter = pK_Navigaion_Id.HasValue ?
                new ObjectParameter("PK_Navigaion_Id", pK_Navigaion_Id) :
                new ObjectParameter("PK_Navigaion_Id", typeof(int));
    
            var navigation_Menu_NameParameter = navigation_Menu_Name != null ?
                new ObjectParameter("Navigation_Menu_Name", navigation_Menu_Name) :
                new ObjectParameter("Navigation_Menu_Name", typeof(string));
    
            var navigation_DescriptionParameter = navigation_Description != null ?
                new ObjectParameter("Navigation_Description", navigation_Description) :
                new ObjectParameter("Navigation_Description", typeof(string));
    
            var navigation_URLParameter = navigation_URL != null ?
                new ObjectParameter("Navigation_URL", navigation_URL) :
                new ObjectParameter("Navigation_URL", typeof(string));
    
            var navigation_Parent_IdParameter = navigation_Parent_Id.HasValue ?
                new ObjectParameter("Navigation_Parent_Id", navigation_Parent_Id) :
                new ObjectParameter("Navigation_Parent_Id", typeof(int));
    
            var fK_Designation_IdParameter = fK_Designation_Id.HasValue ?
                new ObjectParameter("FK_Designation_Id", fK_Designation_Id) :
                new ObjectParameter("FK_Designation_Id", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(int));
    
            var created_DateParameter = created_Date.HasValue ?
                new ObjectParameter("Created_Date", created_Date) :
                new ObjectParameter("Created_Date", typeof(System.DateTime));
    
            var modified_ByParameter = modified_By.HasValue ?
                new ObjectParameter("Modified_By", modified_By) :
                new ObjectParameter("Modified_By", typeof(int));
    
            var modified_DateParameter = modified_Date.HasValue ?
                new ObjectParameter("Modified_Date", modified_Date) :
                new ObjectParameter("Modified_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_Navigation_Result>("W2S_SP_Master_Navigation", actionParameter, pK_Navigaion_IdParameter, navigation_Menu_NameParameter, navigation_DescriptionParameter, navigation_URLParameter, navigation_Parent_IdParameter, fK_Designation_IdParameter, isActiveParameter, created_ByParameter, created_DateParameter, modified_ByParameter, modified_DateParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_Navigation_Map_Result> W2S_SP_Master_Navigation_Map(string action, Nullable<int> pK_Navigaion_Role_Id, Nullable<int> pK_Navigaion_Id, Nullable<int> fK_Designation_Id, string mENULIST)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var pK_Navigaion_Role_IdParameter = pK_Navigaion_Role_Id.HasValue ?
                new ObjectParameter("PK_Navigaion_Role_Id", pK_Navigaion_Role_Id) :
                new ObjectParameter("PK_Navigaion_Role_Id", typeof(int));
    
            var pK_Navigaion_IdParameter = pK_Navigaion_Id.HasValue ?
                new ObjectParameter("PK_Navigaion_Id", pK_Navigaion_Id) :
                new ObjectParameter("PK_Navigaion_Id", typeof(int));
    
            var fK_Designation_IdParameter = fK_Designation_Id.HasValue ?
                new ObjectParameter("FK_Designation_Id", fK_Designation_Id) :
                new ObjectParameter("FK_Designation_Id", typeof(int));
    
            var mENULISTParameter = mENULIST != null ?
                new ObjectParameter("MENULIST", mENULIST) :
                new ObjectParameter("MENULIST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_Navigation_Map_Result>("W2S_SP_Master_Navigation_Map", actionParameter, pK_Navigaion_Role_IdParameter, pK_Navigaion_IdParameter, fK_Designation_IdParameter, mENULISTParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_Product_Result> W2S_SP_Master_Product(string product_Name, string product_Desc, string aCTION, Nullable<int> isActive, Nullable<int> created_By, Nullable<System.DateTime> created_Date, Nullable<int> modified_By, Nullable<System.DateTime> modified_Date, Nullable<int> product_Id)
        {
            var product_NameParameter = product_Name != null ?
                new ObjectParameter("Product_Name", product_Name) :
                new ObjectParameter("Product_Name", typeof(string));
    
            var product_DescParameter = product_Desc != null ?
                new ObjectParameter("Product_Desc", product_Desc) :
                new ObjectParameter("Product_Desc", typeof(string));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(int));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(int));
    
            var created_DateParameter = created_Date.HasValue ?
                new ObjectParameter("Created_Date", created_Date) :
                new ObjectParameter("Created_Date", typeof(System.DateTime));
    
            var modified_ByParameter = modified_By.HasValue ?
                new ObjectParameter("Modified_By", modified_By) :
                new ObjectParameter("Modified_By", typeof(int));
    
            var modified_DateParameter = modified_Date.HasValue ?
                new ObjectParameter("Modified_Date", modified_Date) :
                new ObjectParameter("Modified_Date", typeof(System.DateTime));
    
            var product_IdParameter = product_Id.HasValue ?
                new ObjectParameter("Product_Id", product_Id) :
                new ObjectParameter("Product_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_Product_Result>("W2S_SP_Master_Product", product_NameParameter, product_DescParameter, aCTIONParameter, isActiveParameter, created_ByParameter, created_DateParameter, modified_ByParameter, modified_DateParameter, product_IdParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_Range_Mapping_Result> W2S_SP_Master_Range_Mapping(string action, string fK_W2S_List_Id, Nullable<int> pK_SubRange_Id, Nullable<int> fK_Parent_Id, string user_Designations)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var fK_W2S_List_IdParameter = fK_W2S_List_Id != null ?
                new ObjectParameter("FK_W2S_List_Id", fK_W2S_List_Id) :
                new ObjectParameter("FK_W2S_List_Id", typeof(string));
    
            var pK_SubRange_IdParameter = pK_SubRange_Id.HasValue ?
                new ObjectParameter("PK_SubRange_Id", pK_SubRange_Id) :
                new ObjectParameter("PK_SubRange_Id", typeof(int));
    
            var fK_Parent_IdParameter = fK_Parent_Id.HasValue ?
                new ObjectParameter("FK_Parent_Id", fK_Parent_Id) :
                new ObjectParameter("FK_Parent_Id", typeof(int));
    
            var user_DesignationsParameter = user_Designations != null ?
                new ObjectParameter("User_Designations", user_Designations) :
                new ObjectParameter("User_Designations", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_Range_Mapping_Result>("W2S_SP_Master_Range_Mapping", actionParameter, fK_W2S_List_IdParameter, pK_SubRange_IdParameter, fK_Parent_IdParameter, user_DesignationsParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_RangeType_Result> W2S_SP_Master_RangeType(string aCTION)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_RangeType_Result>("W2S_SP_Master_RangeType", aCTIONParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_Resource_Result> W2S_SP_Master_Resource(string action, Nullable<int> pK_Resource_Id, Nullable<int> fK_Designation_Id, Nullable<int> fK_Zone_Id, Nullable<int> fK_State_Id, string resource_Name, string resource_Login_Id, string resource_Password, string resource_Mobile_No, string navigation_Parent_Id, string resource_Email_Id, Nullable<int> isActive, Nullable<int> created_By, Nullable<System.DateTime> created_Date, Nullable<int> modified_By, Nullable<System.DateTime> modified_Date)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var pK_Resource_IdParameter = pK_Resource_Id.HasValue ?
                new ObjectParameter("PK_Resource_Id", pK_Resource_Id) :
                new ObjectParameter("PK_Resource_Id", typeof(int));
    
            var fK_Designation_IdParameter = fK_Designation_Id.HasValue ?
                new ObjectParameter("FK_Designation_Id", fK_Designation_Id) :
                new ObjectParameter("FK_Designation_Id", typeof(int));
    
            var fK_Zone_IdParameter = fK_Zone_Id.HasValue ?
                new ObjectParameter("FK_Zone_Id", fK_Zone_Id) :
                new ObjectParameter("FK_Zone_Id", typeof(int));
    
            var fK_State_IdParameter = fK_State_Id.HasValue ?
                new ObjectParameter("FK_State_Id", fK_State_Id) :
                new ObjectParameter("FK_State_Id", typeof(int));
    
            var resource_NameParameter = resource_Name != null ?
                new ObjectParameter("Resource_Name", resource_Name) :
                new ObjectParameter("Resource_Name", typeof(string));
    
            var resource_Login_IdParameter = resource_Login_Id != null ?
                new ObjectParameter("Resource_Login_Id", resource_Login_Id) :
                new ObjectParameter("Resource_Login_Id", typeof(string));
    
            var resource_PasswordParameter = resource_Password != null ?
                new ObjectParameter("Resource_Password", resource_Password) :
                new ObjectParameter("Resource_Password", typeof(string));
    
            var resource_Mobile_NoParameter = resource_Mobile_No != null ?
                new ObjectParameter("Resource_Mobile_No", resource_Mobile_No) :
                new ObjectParameter("Resource_Mobile_No", typeof(string));
    
            var navigation_Parent_IdParameter = navigation_Parent_Id != null ?
                new ObjectParameter("Navigation_Parent_Id", navigation_Parent_Id) :
                new ObjectParameter("Navigation_Parent_Id", typeof(string));
    
            var resource_Email_IdParameter = resource_Email_Id != null ?
                new ObjectParameter("Resource_Email_Id", resource_Email_Id) :
                new ObjectParameter("Resource_Email_Id", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(int));
    
            var created_DateParameter = created_Date.HasValue ?
                new ObjectParameter("Created_Date", created_Date) :
                new ObjectParameter("Created_Date", typeof(System.DateTime));
    
            var modified_ByParameter = modified_By.HasValue ?
                new ObjectParameter("Modified_By", modified_By) :
                new ObjectParameter("Modified_By", typeof(int));
    
            var modified_DateParameter = modified_Date.HasValue ?
                new ObjectParameter("Modified_Date", modified_Date) :
                new ObjectParameter("Modified_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_Resource_Result>("W2S_SP_Master_Resource", actionParameter, pK_Resource_IdParameter, fK_Designation_IdParameter, fK_Zone_IdParameter, fK_State_IdParameter, resource_NameParameter, resource_Login_IdParameter, resource_PasswordParameter, resource_Mobile_NoParameter, navigation_Parent_IdParameter, resource_Email_IdParameter, isActiveParameter, created_ByParameter, created_DateParameter, modified_ByParameter, modified_DateParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_Resource_Map_Result> W2S_SP_Master_Resource_Map(string action, Nullable<int> fK_Designation_Id, Nullable<int> fK_Zone_Id, Nullable<int> fK_State_Id, Nullable<int> fK_Resource_Id, Nullable<int> fK_Parent_Id, string user_Designations)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var fK_Designation_IdParameter = fK_Designation_Id.HasValue ?
                new ObjectParameter("FK_Designation_Id", fK_Designation_Id) :
                new ObjectParameter("FK_Designation_Id", typeof(int));
    
            var fK_Zone_IdParameter = fK_Zone_Id.HasValue ?
                new ObjectParameter("FK_Zone_Id", fK_Zone_Id) :
                new ObjectParameter("FK_Zone_Id", typeof(int));
    
            var fK_State_IdParameter = fK_State_Id.HasValue ?
                new ObjectParameter("FK_State_Id", fK_State_Id) :
                new ObjectParameter("FK_State_Id", typeof(int));
    
            var fK_Resource_IdParameter = fK_Resource_Id.HasValue ?
                new ObjectParameter("FK_Resource_Id", fK_Resource_Id) :
                new ObjectParameter("FK_Resource_Id", typeof(int));
    
            var fK_Parent_IdParameter = fK_Parent_Id.HasValue ?
                new ObjectParameter("FK_Parent_Id", fK_Parent_Id) :
                new ObjectParameter("FK_Parent_Id", typeof(int));
    
            var user_DesignationsParameter = user_Designations != null ?
                new ObjectParameter("User_Designations", user_Designations) :
                new ObjectParameter("User_Designations", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_Resource_Map_Result>("W2S_SP_Master_Resource_Map", actionParameter, fK_Designation_IdParameter, fK_Zone_IdParameter, fK_State_IdParameter, fK_Resource_IdParameter, fK_Parent_IdParameter, user_DesignationsParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Master_SubRange_Result> W2S_SP_Master_SubRange(string fK_W2S_List_Id, string subRange_Name, string subRange_Description, Nullable<int> isActive, string aCTION, Nullable<int> pK_SubRange_Id, Nullable<int> created_By, Nullable<System.DateTime> created_Date, Nullable<int> modified_By, Nullable<System.DateTime> modified_Date)
        {
            var fK_W2S_List_IdParameter = fK_W2S_List_Id != null ?
                new ObjectParameter("FK_W2S_List_Id", fK_W2S_List_Id) :
                new ObjectParameter("FK_W2S_List_Id", typeof(string));
    
            var subRange_NameParameter = subRange_Name != null ?
                new ObjectParameter("SubRange_Name", subRange_Name) :
                new ObjectParameter("SubRange_Name", typeof(string));
    
            var subRange_DescriptionParameter = subRange_Description != null ?
                new ObjectParameter("SubRange_Description", subRange_Description) :
                new ObjectParameter("SubRange_Description", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(int));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var pK_SubRange_IdParameter = pK_SubRange_Id.HasValue ?
                new ObjectParameter("PK_SubRange_Id", pK_SubRange_Id) :
                new ObjectParameter("PK_SubRange_Id", typeof(int));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(int));
    
            var created_DateParameter = created_Date.HasValue ?
                new ObjectParameter("Created_Date", created_Date) :
                new ObjectParameter("Created_Date", typeof(System.DateTime));
    
            var modified_ByParameter = modified_By.HasValue ?
                new ObjectParameter("Modified_By", modified_By) :
                new ObjectParameter("Modified_By", typeof(int));
    
            var modified_DateParameter = modified_Date.HasValue ?
                new ObjectParameter("Modified_Date", modified_Date) :
                new ObjectParameter("Modified_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Master_SubRange_Result>("W2S_SP_Master_SubRange", fK_W2S_List_IdParameter, subRange_NameParameter, subRange_DescriptionParameter, isActiveParameter, aCTIONParameter, pK_SubRange_IdParameter, created_ByParameter, created_DateParameter, modified_ByParameter, modified_DateParameter);
        }
    
        public virtual ObjectResult<W2S_SP_MASTER_USER_Result> W2S_SP_MASTER_USER(string action, Nullable<int> pK_Resource_Id, Nullable<int> fK_Designation_Id, Nullable<int> fK_Zone_Id, Nullable<int> fK_State_Id, string resource_Name, string resource_Login_Id, string resource_Password, string resource_Mobile_No, string navigation_Parent_Id, string resource_Email_Id, Nullable<int> isActive, Nullable<int> created_By, Nullable<System.DateTime> created_Date, Nullable<int> modified_By, Nullable<System.DateTime> modified_Date)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var pK_Resource_IdParameter = pK_Resource_Id.HasValue ?
                new ObjectParameter("PK_Resource_Id", pK_Resource_Id) :
                new ObjectParameter("PK_Resource_Id", typeof(int));
    
            var fK_Designation_IdParameter = fK_Designation_Id.HasValue ?
                new ObjectParameter("FK_Designation_Id", fK_Designation_Id) :
                new ObjectParameter("FK_Designation_Id", typeof(int));
    
            var fK_Zone_IdParameter = fK_Zone_Id.HasValue ?
                new ObjectParameter("FK_Zone_Id", fK_Zone_Id) :
                new ObjectParameter("FK_Zone_Id", typeof(int));
    
            var fK_State_IdParameter = fK_State_Id.HasValue ?
                new ObjectParameter("FK_State_Id", fK_State_Id) :
                new ObjectParameter("FK_State_Id", typeof(int));
    
            var resource_NameParameter = resource_Name != null ?
                new ObjectParameter("Resource_Name", resource_Name) :
                new ObjectParameter("Resource_Name", typeof(string));
    
            var resource_Login_IdParameter = resource_Login_Id != null ?
                new ObjectParameter("Resource_Login_Id", resource_Login_Id) :
                new ObjectParameter("Resource_Login_Id", typeof(string));
    
            var resource_PasswordParameter = resource_Password != null ?
                new ObjectParameter("Resource_Password", resource_Password) :
                new ObjectParameter("Resource_Password", typeof(string));
    
            var resource_Mobile_NoParameter = resource_Mobile_No != null ?
                new ObjectParameter("Resource_Mobile_No", resource_Mobile_No) :
                new ObjectParameter("Resource_Mobile_No", typeof(string));
    
            var navigation_Parent_IdParameter = navigation_Parent_Id != null ?
                new ObjectParameter("Navigation_Parent_Id", navigation_Parent_Id) :
                new ObjectParameter("Navigation_Parent_Id", typeof(string));
    
            var resource_Email_IdParameter = resource_Email_Id != null ?
                new ObjectParameter("Resource_Email_Id", resource_Email_Id) :
                new ObjectParameter("Resource_Email_Id", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(int));
    
            var created_DateParameter = created_Date.HasValue ?
                new ObjectParameter("Created_Date", created_Date) :
                new ObjectParameter("Created_Date", typeof(System.DateTime));
    
            var modified_ByParameter = modified_By.HasValue ?
                new ObjectParameter("Modified_By", modified_By) :
                new ObjectParameter("Modified_By", typeof(int));
    
            var modified_DateParameter = modified_Date.HasValue ?
                new ObjectParameter("Modified_Date", modified_Date) :
                new ObjectParameter("Modified_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_MASTER_USER_Result>("W2S_SP_MASTER_USER", actionParameter, pK_Resource_IdParameter, fK_Designation_IdParameter, fK_Zone_IdParameter, fK_State_IdParameter, resource_NameParameter, resource_Login_IdParameter, resource_PasswordParameter, resource_Mobile_NoParameter, navigation_Parent_IdParameter, resource_Email_IdParameter, isActiveParameter, created_ByParameter, created_DateParameter, modified_ByParameter, modified_DateParameter);
        }
    
        public virtual int W2S_SP_Nav_Role_Map(string action, Nullable<int> pK_Navigation_Role_Id, Nullable<int> fK_Navigation_Id, Nullable<int> fK_Designation_Id, Nullable<int> isActive, Nullable<int> created_By, Nullable<System.DateTime> created_Date, Nullable<int> modified_By, Nullable<System.DateTime> modified_Date, string mENULIST)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var pK_Navigation_Role_IdParameter = pK_Navigation_Role_Id.HasValue ?
                new ObjectParameter("PK_Navigation_Role_Id", pK_Navigation_Role_Id) :
                new ObjectParameter("PK_Navigation_Role_Id", typeof(int));
    
            var fK_Navigation_IdParameter = fK_Navigation_Id.HasValue ?
                new ObjectParameter("FK_Navigation_Id", fK_Navigation_Id) :
                new ObjectParameter("FK_Navigation_Id", typeof(int));
    
            var fK_Designation_IdParameter = fK_Designation_Id.HasValue ?
                new ObjectParameter("FK_Designation_Id", fK_Designation_Id) :
                new ObjectParameter("FK_Designation_Id", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(int));
    
            var created_DateParameter = created_Date.HasValue ?
                new ObjectParameter("Created_Date", created_Date) :
                new ObjectParameter("Created_Date", typeof(System.DateTime));
    
            var modified_ByParameter = modified_By.HasValue ?
                new ObjectParameter("Modified_By", modified_By) :
                new ObjectParameter("Modified_By", typeof(int));
    
            var modified_DateParameter = modified_Date.HasValue ?
                new ObjectParameter("Modified_Date", modified_Date) :
                new ObjectParameter("Modified_Date", typeof(System.DateTime));
    
            var mENULISTParameter = mENULIST != null ?
                new ObjectParameter("MENULIST", mENULIST) :
                new ObjectParameter("MENULIST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("W2S_SP_Nav_Role_Map", actionParameter, pK_Navigation_Role_IdParameter, fK_Navigation_IdParameter, fK_Designation_IdParameter, isActiveParameter, created_ByParameter, created_DateParameter, modified_ByParameter, modified_DateParameter, mENULISTParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Opportunity_Result> W2S_SP_Opportunity(Nullable<int> pK_Opportunity_Id, Nullable<int> fK_Customer_Id, string customer_Contact_No, Nullable<int> fK_Opportunity_Source, Nullable<int> fK_Opportunity_Type, string opportunity_Name, Nullable<System.DateTime> start_Date, Nullable<int> expected_Value, string chance_Of_Success, string sales_Phase, Nullable<System.DateTime> follow_Up_Date, Nullable<System.DateTime> closed_Date, string fK_Status, string aCTION, Nullable<bool> forecast, Nullable<int> fK_Opportunity_Id, string fK_Visit_Type_Id, Nullable<System.DateTime> list_Visit_Start_Date, string list_Visit_Start_Time, Nullable<System.DateTime> list_Visit_End_Date, string list_Visit_End_Time, Nullable<int> pK_Visit, Nullable<int> pK_Competitor_Id, string fK_Competitor_Type_Id, Nullable<int> fK_Competitor_Id, Nullable<bool> is_Main, string comp_Product, string comp_Price, string file_Name, Nullable<int> pK_Quotation_Id, Nullable<int> pK_Document_Id, Nullable<long> won_Value, string won_Remarks, Nullable<long> lost_Value, Nullable<int> fK_Lost_Competitor_Id, string lost_Remarks, string fK_Stop_Reason, Nullable<int> fK_Stop_Competitor_Id, string stop_Remarks, string fK_Range_Id, Nullable<int> fK_Sub_Range_Id, Nullable<int> quantity, string price, Nullable<int> fK_Product_Id, Nullable<int> created_By)
        {
            var pK_Opportunity_IdParameter = pK_Opportunity_Id.HasValue ?
                new ObjectParameter("PK_Opportunity_Id", pK_Opportunity_Id) :
                new ObjectParameter("PK_Opportunity_Id", typeof(int));
    
            var fK_Customer_IdParameter = fK_Customer_Id.HasValue ?
                new ObjectParameter("FK_Customer_Id", fK_Customer_Id) :
                new ObjectParameter("FK_Customer_Id", typeof(int));
    
            var customer_Contact_NoParameter = customer_Contact_No != null ?
                new ObjectParameter("Customer_Contact_No", customer_Contact_No) :
                new ObjectParameter("Customer_Contact_No", typeof(string));
    
            var fK_Opportunity_SourceParameter = fK_Opportunity_Source.HasValue ?
                new ObjectParameter("FK_Opportunity_Source", fK_Opportunity_Source) :
                new ObjectParameter("FK_Opportunity_Source", typeof(int));
    
            var fK_Opportunity_TypeParameter = fK_Opportunity_Type.HasValue ?
                new ObjectParameter("FK_Opportunity_Type", fK_Opportunity_Type) :
                new ObjectParameter("FK_Opportunity_Type", typeof(int));
    
            var opportunity_NameParameter = opportunity_Name != null ?
                new ObjectParameter("Opportunity_Name", opportunity_Name) :
                new ObjectParameter("Opportunity_Name", typeof(string));
    
            var start_DateParameter = start_Date.HasValue ?
                new ObjectParameter("Start_Date", start_Date) :
                new ObjectParameter("Start_Date", typeof(System.DateTime));
    
            var expected_ValueParameter = expected_Value.HasValue ?
                new ObjectParameter("Expected_Value", expected_Value) :
                new ObjectParameter("Expected_Value", typeof(int));
    
            var chance_Of_SuccessParameter = chance_Of_Success != null ?
                new ObjectParameter("Chance_Of_Success", chance_Of_Success) :
                new ObjectParameter("Chance_Of_Success", typeof(string));
    
            var sales_PhaseParameter = sales_Phase != null ?
                new ObjectParameter("Sales_Phase", sales_Phase) :
                new ObjectParameter("Sales_Phase", typeof(string));
    
            var follow_Up_DateParameter = follow_Up_Date.HasValue ?
                new ObjectParameter("Follow_Up_Date", follow_Up_Date) :
                new ObjectParameter("Follow_Up_Date", typeof(System.DateTime));
    
            var closed_DateParameter = closed_Date.HasValue ?
                new ObjectParameter("Closed_Date", closed_Date) :
                new ObjectParameter("Closed_Date", typeof(System.DateTime));
    
            var fK_StatusParameter = fK_Status != null ?
                new ObjectParameter("FK_Status", fK_Status) :
                new ObjectParameter("FK_Status", typeof(string));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var forecastParameter = forecast.HasValue ?
                new ObjectParameter("Forecast", forecast) :
                new ObjectParameter("Forecast", typeof(bool));
    
            var fK_Opportunity_IdParameter = fK_Opportunity_Id.HasValue ?
                new ObjectParameter("FK_Opportunity_Id", fK_Opportunity_Id) :
                new ObjectParameter("FK_Opportunity_Id", typeof(int));
    
            var fK_Visit_Type_IdParameter = fK_Visit_Type_Id != null ?
                new ObjectParameter("FK_Visit_Type_Id", fK_Visit_Type_Id) :
                new ObjectParameter("FK_Visit_Type_Id", typeof(string));
    
            var list_Visit_Start_DateParameter = list_Visit_Start_Date.HasValue ?
                new ObjectParameter("List_Visit_Start_Date", list_Visit_Start_Date) :
                new ObjectParameter("List_Visit_Start_Date", typeof(System.DateTime));
    
            var list_Visit_Start_TimeParameter = list_Visit_Start_Time != null ?
                new ObjectParameter("List_Visit_Start_Time", list_Visit_Start_Time) :
                new ObjectParameter("List_Visit_Start_Time", typeof(string));
    
            var list_Visit_End_DateParameter = list_Visit_End_Date.HasValue ?
                new ObjectParameter("List_Visit_End_Date", list_Visit_End_Date) :
                new ObjectParameter("List_Visit_End_Date", typeof(System.DateTime));
    
            var list_Visit_End_TimeParameter = list_Visit_End_Time != null ?
                new ObjectParameter("List_Visit_End_Time", list_Visit_End_Time) :
                new ObjectParameter("List_Visit_End_Time", typeof(string));
    
            var pK_VisitParameter = pK_Visit.HasValue ?
                new ObjectParameter("PK_Visit", pK_Visit) :
                new ObjectParameter("PK_Visit", typeof(int));
    
            var pK_Competitor_IdParameter = pK_Competitor_Id.HasValue ?
                new ObjectParameter("PK_Competitor_Id", pK_Competitor_Id) :
                new ObjectParameter("PK_Competitor_Id", typeof(int));
    
            var fK_Competitor_Type_IdParameter = fK_Competitor_Type_Id != null ?
                new ObjectParameter("FK_Competitor_Type_Id", fK_Competitor_Type_Id) :
                new ObjectParameter("FK_Competitor_Type_Id", typeof(string));
    
            var fK_Competitor_IdParameter = fK_Competitor_Id.HasValue ?
                new ObjectParameter("FK_Competitor_Id", fK_Competitor_Id) :
                new ObjectParameter("FK_Competitor_Id", typeof(int));
    
            var is_MainParameter = is_Main.HasValue ?
                new ObjectParameter("Is_Main", is_Main) :
                new ObjectParameter("Is_Main", typeof(bool));
    
            var comp_ProductParameter = comp_Product != null ?
                new ObjectParameter("Comp_Product", comp_Product) :
                new ObjectParameter("Comp_Product", typeof(string));
    
            var comp_PriceParameter = comp_Price != null ?
                new ObjectParameter("Comp_Price", comp_Price) :
                new ObjectParameter("Comp_Price", typeof(string));
    
            var file_NameParameter = file_Name != null ?
                new ObjectParameter("File_Name", file_Name) :
                new ObjectParameter("File_Name", typeof(string));
    
            var pK_Quotation_IdParameter = pK_Quotation_Id.HasValue ?
                new ObjectParameter("PK_Quotation_Id", pK_Quotation_Id) :
                new ObjectParameter("PK_Quotation_Id", typeof(int));
    
            var pK_Document_IdParameter = pK_Document_Id.HasValue ?
                new ObjectParameter("PK_Document_Id", pK_Document_Id) :
                new ObjectParameter("PK_Document_Id", typeof(int));
    
            var won_ValueParameter = won_Value.HasValue ?
                new ObjectParameter("Won_Value", won_Value) :
                new ObjectParameter("Won_Value", typeof(long));
    
            var won_RemarksParameter = won_Remarks != null ?
                new ObjectParameter("Won_Remarks", won_Remarks) :
                new ObjectParameter("Won_Remarks", typeof(string));
    
            var lost_ValueParameter = lost_Value.HasValue ?
                new ObjectParameter("Lost_Value", lost_Value) :
                new ObjectParameter("Lost_Value", typeof(long));
    
            var fK_Lost_Competitor_IdParameter = fK_Lost_Competitor_Id.HasValue ?
                new ObjectParameter("FK_Lost_Competitor_Id", fK_Lost_Competitor_Id) :
                new ObjectParameter("FK_Lost_Competitor_Id", typeof(int));
    
            var lost_RemarksParameter = lost_Remarks != null ?
                new ObjectParameter("Lost_Remarks", lost_Remarks) :
                new ObjectParameter("Lost_Remarks", typeof(string));
    
            var fK_Stop_ReasonParameter = fK_Stop_Reason != null ?
                new ObjectParameter("FK_Stop_Reason", fK_Stop_Reason) :
                new ObjectParameter("FK_Stop_Reason", typeof(string));
    
            var fK_Stop_Competitor_IdParameter = fK_Stop_Competitor_Id.HasValue ?
                new ObjectParameter("FK_Stop_Competitor_Id", fK_Stop_Competitor_Id) :
                new ObjectParameter("FK_Stop_Competitor_Id", typeof(int));
    
            var stop_RemarksParameter = stop_Remarks != null ?
                new ObjectParameter("Stop_Remarks", stop_Remarks) :
                new ObjectParameter("Stop_Remarks", typeof(string));
    
            var fK_Range_IdParameter = fK_Range_Id != null ?
                new ObjectParameter("FK_Range_Id", fK_Range_Id) :
                new ObjectParameter("FK_Range_Id", typeof(string));
    
            var fK_Sub_Range_IdParameter = fK_Sub_Range_Id.HasValue ?
                new ObjectParameter("FK_Sub_Range_Id", fK_Sub_Range_Id) :
                new ObjectParameter("FK_Sub_Range_Id", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            var priceParameter = price != null ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(string));
    
            var fK_Product_IdParameter = fK_Product_Id.HasValue ?
                new ObjectParameter("FK_Product_Id", fK_Product_Id) :
                new ObjectParameter("FK_Product_Id", typeof(int));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Opportunity_Result>("W2S_SP_Opportunity", pK_Opportunity_IdParameter, fK_Customer_IdParameter, customer_Contact_NoParameter, fK_Opportunity_SourceParameter, fK_Opportunity_TypeParameter, opportunity_NameParameter, start_DateParameter, expected_ValueParameter, chance_Of_SuccessParameter, sales_PhaseParameter, follow_Up_DateParameter, closed_DateParameter, fK_StatusParameter, aCTIONParameter, forecastParameter, fK_Opportunity_IdParameter, fK_Visit_Type_IdParameter, list_Visit_Start_DateParameter, list_Visit_Start_TimeParameter, list_Visit_End_DateParameter, list_Visit_End_TimeParameter, pK_VisitParameter, pK_Competitor_IdParameter, fK_Competitor_Type_IdParameter, fK_Competitor_IdParameter, is_MainParameter, comp_ProductParameter, comp_PriceParameter, file_NameParameter, pK_Quotation_IdParameter, pK_Document_IdParameter, won_ValueParameter, won_RemarksParameter, lost_ValueParameter, fK_Lost_Competitor_IdParameter, lost_RemarksParameter, fK_Stop_ReasonParameter, fK_Stop_Competitor_IdParameter, stop_RemarksParameter, fK_Range_IdParameter, fK_Sub_Range_IdParameter, quantityParameter, priceParameter, fK_Product_IdParameter, created_ByParameter);
        }
    
        public virtual ObjectResult<W2S_SP_RangeType_Result> W2S_SP_RangeType(string aCTION)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_RangeType_Result>("W2S_SP_RangeType", aCTIONParameter);
        }
    
        public virtual ObjectResult<W2S_SP_Reset_Password_Result> W2S_SP_Reset_Password(Nullable<int> user_ID, string nEWPassword, string aCTION)
        {
            var user_IDParameter = user_ID.HasValue ?
                new ObjectParameter("User_ID", user_ID) :
                new ObjectParameter("User_ID", typeof(int));
    
            var nEWPasswordParameter = nEWPassword != null ?
                new ObjectParameter("NEWPassword", nEWPassword) :
                new ObjectParameter("NEWPassword", typeof(string));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_Reset_Password_Result>("W2S_SP_Reset_Password", user_IDParameter, nEWPasswordParameter, aCTIONParameter);
        }
    
        public virtual int W2S_SP_Reset_Password2(Nullable<int> user_ID, string nEWPassword, string aCTION)
        {
            var user_IDParameter = user_ID.HasValue ?
                new ObjectParameter("User_ID", user_ID) :
                new ObjectParameter("User_ID", typeof(int));
    
            var nEWPasswordParameter = nEWPassword != null ?
                new ObjectParameter("NEWPassword", nEWPassword) :
                new ObjectParameter("NEWPassword", typeof(string));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("W2S_SP_Reset_Password2", user_IDParameter, nEWPasswordParameter, aCTIONParameter);
        }
    
        public virtual ObjectResult<W2S_SP_ROOT_MENU_LIST_Result> W2S_SP_ROOT_MENU_LIST(string action, Nullable<int> pK_Navigaion_Id, string navigation_Menu_Name, string navigation_Description, string navigation_URL, Nullable<int> navigation_Parent_Id, Nullable<int> fK_Designation_Id, Nullable<int> isActive, Nullable<int> created_By, Nullable<System.DateTime> created_Date, Nullable<int> modified_By, Nullable<System.DateTime> modified_Date, Nullable<int> rOLE_ID, Nullable<int> uSERID)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var pK_Navigaion_IdParameter = pK_Navigaion_Id.HasValue ?
                new ObjectParameter("PK_Navigaion_Id", pK_Navigaion_Id) :
                new ObjectParameter("PK_Navigaion_Id", typeof(int));
    
            var navigation_Menu_NameParameter = navigation_Menu_Name != null ?
                new ObjectParameter("Navigation_Menu_Name", navigation_Menu_Name) :
                new ObjectParameter("Navigation_Menu_Name", typeof(string));
    
            var navigation_DescriptionParameter = navigation_Description != null ?
                new ObjectParameter("Navigation_Description", navigation_Description) :
                new ObjectParameter("Navigation_Description", typeof(string));
    
            var navigation_URLParameter = navigation_URL != null ?
                new ObjectParameter("Navigation_URL", navigation_URL) :
                new ObjectParameter("Navigation_URL", typeof(string));
    
            var navigation_Parent_IdParameter = navigation_Parent_Id.HasValue ?
                new ObjectParameter("Navigation_Parent_Id", navigation_Parent_Id) :
                new ObjectParameter("Navigation_Parent_Id", typeof(int));
    
            var fK_Designation_IdParameter = fK_Designation_Id.HasValue ?
                new ObjectParameter("FK_Designation_Id", fK_Designation_Id) :
                new ObjectParameter("FK_Designation_Id", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(int));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(int));
    
            var created_DateParameter = created_Date.HasValue ?
                new ObjectParameter("Created_Date", created_Date) :
                new ObjectParameter("Created_Date", typeof(System.DateTime));
    
            var modified_ByParameter = modified_By.HasValue ?
                new ObjectParameter("Modified_By", modified_By) :
                new ObjectParameter("Modified_By", typeof(int));
    
            var modified_DateParameter = modified_Date.HasValue ?
                new ObjectParameter("Modified_Date", modified_Date) :
                new ObjectParameter("Modified_Date", typeof(System.DateTime));
    
            var rOLE_IDParameter = rOLE_ID.HasValue ?
                new ObjectParameter("ROLE_ID", rOLE_ID) :
                new ObjectParameter("ROLE_ID", typeof(int));
    
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<W2S_SP_ROOT_MENU_LIST_Result>("W2S_SP_ROOT_MENU_LIST", actionParameter, pK_Navigaion_IdParameter, navigation_Menu_NameParameter, navigation_DescriptionParameter, navigation_URLParameter, navigation_Parent_IdParameter, fK_Designation_IdParameter, isActiveParameter, created_ByParameter, created_DateParameter, modified_ByParameter, modified_DateParameter, rOLE_IDParameter, uSERIDParameter);
        }
    }
}
