//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERTYPE
    {
        public int Typ_ID { get; set; }
        public string Type_Name { get; set; }
        public string Type_Detail { get; set; }
        public string Log_Update { get; set; }
        public Nullable<System.DateTime> Time_Stamp_Add_Date { get; set; }
        public Nullable<System.DateTime> Time_Stamp_Update_Date { get; set; }
    }
}
