//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W2S_Customer_Master
    {
        public int PK_Cust_Id { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_Address_Line1 { get; set; }
        public string Cust_Address_Line2 { get; set; }
        public Nullable<int> FK_Zone_Id { get; set; }
        public Nullable<int> FK_State_Id { get; set; }
        public Nullable<int> FK_City_Id { get; set; }
        public string Cust_Longitude { get; set; }
        public string Cust_Latitude { get; set; }
        public string Cust_GSTN_No { get; set; }
        public string Cust_Cmprsd_Air_App { get; set; }
        public string Cust_End_Product { get; set; }
        public string VisitingCardPath { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
    }
}
