//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W2S_Opportunity_Document
    {
        public long PK_Document_Id { get; set; }
        public Nullable<long> FK_Opportunity_Id { get; set; }
        public string File_Name { get; set; }
        public Nullable<System.DateTime> Added_Date { get; set; }
        public Nullable<int> Added_Time { get; set; }
    }
}
