//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W2S__Master_Enquiry
    {
        public int Enqry_Id { get; set; }
        public string Enqry_No { get; set; }
        public Nullable<int> Cust_Id { get; set; }
        public Nullable<int> Enquiry_Source_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> IsQuotationSend { get; set; }
        public string Quotation_Remark { get; set; }
        public Nullable<int> Status_Id { get; set; }
        public string Competitor_Name { get; set; }
        public string Competitor_Desc { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public string Brief { get; set; }
        public string Source { get; set; }
        public string ProductOffered { get; set; }
        public string Range { get; set; }
        public string VisitType { get; set; }
        public string NextVisitDate { get; set; }
        public string NextVisitTime { get; set; }
        public string RecordNotes { get; set; }
        public string EnquiryType { get; set; }
    
        public virtual W2S_Master_EnquirySource W2S_Master_EnquirySource { get; set; }
    }
}
