//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W2S_Opportunity_Product
    {
        public long PK_Oppor_Product_Id { get; set; }
        public Nullable<long> FK_Opportunity_Id { get; set; }
        public string FK_Range_Id { get; set; }
        public Nullable<int> FK_Sub_Range_Id { get; set; }
        public Nullable<int> FK_Product_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Price { get; set; }
        public Nullable<int> Added_By { get; set; }
        public Nullable<System.DateTime> Added_Date { get; set; }
    }
}
