//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W2S_Opportunity_Visits
    {
        public long PK_Visit { get; set; }
        public Nullable<int> FK_Opportunity_Id { get; set; }
        public string FK_Visit_Type_Id { get; set; }
        public Nullable<System.DateTime> List_Visit_Start_Date { get; set; }
        public string List_Visit_Start_Time { get; set; }
        public Nullable<System.DateTime> List_Visit_End_Date { get; set; }
        public string List_Visit_End_Time { get; set; }
        public Nullable<System.DateTime> Added_Date { get; set; }
        public Nullable<int> Added_By { get; set; }
    }
}
