//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W2S_Customer_Contct_Person_Mapping
    {
        public int PK_Cust_CntctPrson_Mapng_Id { get; set; }
        public int FK_Cust_Id { get; set; }
        public Nullable<int> FK_Cust_CntctPrson_Dsgntn_Id { get; set; }
        public string Cust_CntctPrson_Name { get; set; }
        public string Cust_CntctPrson_Contact_No { get; set; }
        public string Cust_CntctPrson_Email_Id { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
    }
}
