//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W2S_Master_City
    {
        public int PK_City_Id { get; set; }
        public Nullable<int> FK_State_Id { get; set; }
        public string City_Name { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
