//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W2S__Master_Navigation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public W2S__Master_Navigation()
        {
            this.W2S__Master_Navigation_Role_Mapping = new HashSet<W2S__Master_Navigation_Role_Mapping>();
        }
    
        public int Navigation_Id { get; set; }
        public string Nevigation_Menu_Name { get; set; }
        public string Nevigation_Description { get; set; }
        public string Nevigation_URL { get; set; }
        public Nullable<int> Nevigation_Parent_Id { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W2S__Master_Navigation_Role_Mapping> W2S__Master_Navigation_Role_Mapping { get; set; }
    }
}
