//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W2S_Opportunity
    {
        public long PK_Opportunity_Id { get; set; }
        public Nullable<int> FK_Customer_Id { get; set; }
        public string Customer_Contact_No { get; set; }
        public Nullable<int> FK_Opportunity_Source { get; set; }
        public Nullable<int> FK_Opportunity_Type { get; set; }
        public string Opportunity_Name { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<int> Expected_Value { get; set; }
        public string Chance_Of_Success { get; set; }
        public string Sales_Phase { get; set; }
        public Nullable<System.DateTime> Follow_Up_Date { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public string FK_Status { get; set; }
        public Nullable<bool> Forecast { get; set; }
        public Nullable<System.DateTime> Added_Date { get; set; }
        public Nullable<int> Added_By { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public Nullable<int> Modify_By { get; set; }
        public Nullable<long> Won_Value { get; set; }
        public string Won_Remarks { get; set; }
        public Nullable<long> Lost_Value { get; set; }
        public Nullable<int> FK_Lost_Competitor_Id { get; set; }
        public string Lost_Remarks { get; set; }
        public string FK_Stop_Reason { get; set; }
        public Nullable<int> FK_Stop_Competitor_Id { get; set; }
        public string Stop_Remarks { get; set; }
    }
}
